(define (problem P3)
(:domain P2P)
(:objects
        comp1 comp2 comp3 comp4  - computer
        A B C D  - file 
)


(:init
  (saved comp1 A)
  (saved comp1 B)
  (saved comp1 C)
  (saved comp1 D)
  (free  comp1  )
  (free  comp2  )
  (free  comp3  )
  (free  comp4  )
  (routed comp1 comp2)
  (routed comp1 comp3)
  (routed comp1 comp4)
  (routed comp2 comp1)
  (routed comp2 comp3)
  (routed comp2 comp4)
  (routed comp3 comp1)
  (routed comp3 comp2)
  (routed comp3 comp4)
  (routed comp4 comp1)
  (routed comp4 comp2)
  (routed comp4 comp3)
  (= (file-size A) 4)
  (= (file-size C) 6)
  (= (file-size B) 6)
  (= (file-size D) 6)
)
(:goal 
   (and
     (saved comp1 A)
     (saved comp2 A)
     (saved comp3 A)
     (saved comp4 A)
     (saved comp1 B)
     (saved comp2 B)
     (saved comp3 B)
     (saved comp4 B)
     (saved comp1 C)
     (saved comp2 C)
     (saved comp3 C)
     (saved comp4 C)
     (saved comp1 D)
     (saved comp2 D)
     (saved comp3 D)
     (saved comp4 D)
	   )
)
)
