(define (problem P3)
(:domain P2P)
(:objects
        comp1 comp2 comp3 comp4 comp5  - computer
        A B C D E  - file 
)


(:init
  (saved comp1 A)
  (saved comp1 B)
  (saved comp1 C)
  (saved comp1 D)
  (saved comp1 E)
  (free  comp1  )
  (free  comp2  )
  (free  comp3  )
  (free  comp4  )
  (free  comp5  )
  (routed comp1 comp2)
  (routed comp1 comp3)
  (routed comp1 comp4)
  (routed comp1 comp5)
  (routed comp2 comp1)
  (routed comp2 comp3)
  (routed comp2 comp4)
  (routed comp2 comp5)
  (routed comp3 comp1)
  (routed comp3 comp2)
  (routed comp3 comp4)
  (routed comp3 comp5)
  (routed comp4 comp1)
  (routed comp4 comp2)
  (routed comp4 comp3)
  (routed comp4 comp5)
  (routed comp5 comp1)
  (routed comp5 comp2)
  (routed comp5 comp3)
  (routed comp5 comp4)
  (= (file-size A) 8)
  (= (file-size C) 7)
  (= (file-size B) 4)
  (= (file-size E) 5)
  (= (file-size D) 8)
)
(:goal 
   (and
     (saved comp1 A)
     (saved comp2 A)
     (saved comp3 A)
     (saved comp4 A)
     (saved comp5 A)
     (saved comp1 B)
     (saved comp2 B)
     (saved comp3 B)
     (saved comp4 B)
     (saved comp5 B)
     (saved comp1 C)
     (saved comp2 C)
     (saved comp3 C)
     (saved comp4 C)
     (saved comp5 C)
     (saved comp1 D)
     (saved comp2 D)
     (saved comp3 D)
     (saved comp4 D)
     (saved comp5 D)
     (saved comp1 E)
     (saved comp2 E)
     (saved comp3 E)
     (saved comp4 E)
     (saved comp5 E)
	   )
)
(:metric minimize (total-time))
)
