;LINEAR TOPOLOGY SETTING
(define (problem P3)
(:domain P2P)
(:objects
        comp1 comp2 comp3 comp4 comp5 comp6  - computer
        file0 file1 file2 file3 file4 file5  - file 
)


(:init
  (saved comp1 file0)
  (saved comp6 file1)
  (saved comp1 file2)
  (saved comp6 file3)
  (saved comp1 file4)
  (saved comp6 file5)
  (free  comp1  )
  (free  comp2  )
  (free  comp3  )
  (free  comp4  )
  (free  comp5  )
  (free  comp6  )
  (routed comp1 comp2)
  (routed comp2 comp1)
  (routed comp2 comp3)
  (routed comp3 comp2)
  (routed comp3 comp4)
  (routed comp4 comp3)
  (routed comp4 comp5)
  (routed comp5 comp4)
  (routed comp5 comp6)
  (routed comp6 comp5)
  (= (file-size file3) 5)
  (= (file-size file2) 5)
  (= (file-size file1) 5)
  (= (file-size file0) 6)
  (= (file-size file5) 5)
  (= (file-size file4) 4)
)
(:goal 
   (and
     (saved comp1 file0)
     (saved comp2 file0)
     (saved comp3 file0)
     (saved comp4 file0)
     (saved comp5 file0)
     (saved comp6 file0)
     (saved comp1 file1)
     (saved comp2 file1)
     (saved comp3 file1)
     (saved comp4 file1)
     (saved comp5 file1)
     (saved comp6 file1)
     (saved comp1 file2)
     (saved comp2 file2)
     (saved comp3 file2)
     (saved comp4 file2)
     (saved comp5 file2)
     (saved comp6 file2)
     (saved comp1 file3)
     (saved comp2 file3)
     (saved comp3 file3)
     (saved comp4 file3)
     (saved comp5 file3)
     (saved comp6 file3)
     (saved comp1 file4)
     (saved comp2 file4)
     (saved comp3 file4)
     (saved comp4 file4)
     (saved comp5 file4)
     (saved comp6 file4)
     (saved comp1 file5)
     (saved comp2 file5)
     (saved comp3 file5)
     (saved comp4 file5)
     (saved comp5 file5)
     (saved comp6 file5)
	   )
)
(:metric minimize (total-time))
)
